### PR TITLE
Feature gianlucagorni

### PR DESCRIPTION
**Pull request by Gwyn77**
pronto per revisione

### CODE REVIEW

**Review by lucapitzoi — CHANGES_REQUESTED** [review]
Leva i simboli del conflitto

**Comment by RealMeliodas** [comment]
image

**Comment by RealMeliodas** [comment]
image

**Comment by matteoDanelli2003** [comment]
image

**Comment by matteoDanelli2003** [comment]
image

**Comment by matteoDanelli2003** [comment]
image

**Comment by matteoDanelli2003** [comment]
image

**Pull request merged**
